[project]
name = "flowstack"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "./.cache"
boot_phi = 1.0
boot_zeta = 2.0

[contracts.flowstack]
path = "contracts/flowstack.clar"
clarity_version = 1

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
